In [ ]:
!nvidia-smi # use this if u have a GPU it will show the info about the GPU

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch

In [ ]:
X = torch.rand(3,4)

In [ ]:
type(X )

torch.Tensor

In [ ]:
scaler = torch.rand(7)
scaler # this has only one dimension

tensor([0.5806, 0.8072, 0.8648, 0.7243, 0.7214, 0.4970, 0.4639])

In [ ]:
#check the dimension of the tensor
scaler.ndim

1

In [ ]:
scaler[5].item()

0.4970031976699829

In [ ]:
vector = torch.rand([7,7])

In [ ]:
vector.ndim

2

In [ ]:
vector

tensor([[0.7144, 0.4280, 0.9419, 0.7387, 0.6070, 0.1245, 0.6495],
        [0.7385, 0.9303, 0.0440, 0.2835, 0.6956, 0.6925, 0.2460],
        [0.5464, 0.9914, 0.6642, 0.3222, 0.0688, 0.1134, 0.0348],
        [0.2995, 0.3836, 0.0508, 0.9770, 0.3339, 0.8337, 0.2591],
        [0.4658, 0.9714, 0.0461, 0.8860, 0.7631, 0.5354, 0.2579],
        [0.4048, 0.5586, 0.6350, 0.6272, 0.5598, 0.0117, 0.3862],
        [0.3654, 0.4517, 0.5116, 0.8145, 0.9564, 0.5210, 0.0392]])

In [ ]:
vector.shape

torch.Size([7, 7])

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
# matrix tensor
X = torch.tensor([[1,2,3],
              [4,5,6]])

In [ ]:
type(X)

torch.Tensor

In [ ]:
X.shape

torch.Size([2, 3])

In [ ]:
X.ndim

2

In [ ]:
 x = torch.range(0,10,2)

<ipython-input-90-b597731eebd1>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(0,10,2)


In [ ]:
x.ndim
x.type

<function Tensor.type>

In [ ]:
import torch
torch = torch.tensor([1,2,3,4])
torch.shape

torch.Size([4])

In [ ]:
import torch
tensor = torch.tensor([1,2,3])

In [ ]:
element_wise = tensor*tensor
element_wise

tensor([1, 4, 9])

In [ ]:
matrix_multiplication = torch.matmul(tensor,tensor)
matrix_multiplication

tensor(14)

In [ ]:
# matrix multiplication by loop
%%time
tensor = torch.tensor(range(1,11,2))
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(165)
CPU times: user 1.42 ms, sys: 0 ns, total: 1.42 ms
Wall time: 1.43 ms


In [ ]:
%%time
tensor = torch.tensor(range(1,11,2))
vlaue = torch.matmul(tensor,tensor)
print(value)

tensor(165)
CPU times: user 1.29 ms, sys: 0 ns, total: 1.29 ms
Wall time: 1.29 ms


In [ ]:
# tensor_A = torch.tensor([[1,1],
#                          [12,13],
#                          [16,17]])
# tensor_B = torch.tensor([[1,2],
#                        [4,5],
#                        [7,8]])



# new_tensor_mutl = torch.matmul(tensor_A,tensor_B)
# new_tensor_mutl

In [ ]:
# to avoid the above error we need to transpose the matrix which we desire to multiply
tensor = tensor_A.T
tensor

tensor([[ 1, 12, 16],
        [ 1, 13, 17]])

In [ ]:
new_tensor_mutl = torch.matmul(tensor,tensor_B)
new_tensor_mutl

tensor([[161, 190],
        [172, 203]])

In [ ]:
A = torch.rand([2,3])

In [ ]:
A

tensor([[0.8623, 0.5299, 0.6759],
        [0.7716, 0.5361, 0.2493]])

In [ ]:
B = torch.rand([2,3])

In [ ]:
B

tensor([[1.0000, 0.8952, 0.0954],
        [0.4130, 0.9539, 0.4598]])

In [ ]:
# now multiply all a and b
# A*B this happens because it is an element wise multiplication
# C = torch.matmul(A,B) # This do not happen because the the dimensions are not matching together

# C

In [ ]:
#To do the above mlt we need to transopose one of the matrix
X =  torch.mm(A.T,B)#mm is the short form for the matmul
X

tensor([[1.1810, 1.5080, 0.4371],
        [0.7513, 0.9858, 0.2971],
        [0.7788, 0.8428, 0.1791]])

In [ ]:
x.type

<function Tensor.type>

In [ ]:
print(torch.__version__)

2.3.0+cu121


In [ ]:
torch.range(0,10)

<ipython-input-109-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
import torch
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

In [ ]:
torch.manual_seed(42)
linear - tor

In [ ]:
import torch
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A.float() # Convert tensor_A to float
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.6499,  0.5797,  0.3287, -0.0288,  0.6497,  0.8515],
        [14.6395,  6.5521,  0.3367,  1.1676,  1.2814,  9.2003],
        [19.1496,  8.4877,  0.2878,  1.4516,  1.6998, 12.1882]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
import torch
x = torch.tensor([1.,8.])
x

tensor([1., 8.])

In [ ]:
x = torch.arange(1.,8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
x.shape


torch.Size([7])

In [ ]:
# now let us add xtra dimensions with torch.reshape
x_reshaped = x.reshape(1,7)
x_reshaped.shape

torch.Size([1, 7])

In [ ]:
#By the number of brackets we can say number if dimensions
# Change view and keep the data as original
z = x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# changing the z changes the x
z[:, 0 ] = 5
z,x # Both the x and z has changed the positional value

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# stack the tensor on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# To squeez the above tensor means that we remove all the single dimensionos
x_squeezed = x_reshaped.squeeze()
print(x_reshaped,"this is the previous one ", x_reshaped.shape , "this is the previsous shape ")

tensor([[5., 2., 3., 4., 5., 6., 7.]]) this is the previous one  torch.Size([1, 7]) this is the previsous shape 


In [ ]:
print(x_squeezed, "this is after the squeez ", x_squeezed.shape , " the is the new shape ")# this has removed the dimension in the above 1, 7 tensor

tensor([5., 2., 3., 4., 5., 6., 7.]) this is after the squeez  torch.Size([7])  the is the new shape 


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed.shape # same as the above but to unsqueez the the degree

torch.Size([1, 7])

In [147]:
import torch
import numpy as np
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
tensor # while converting from numpy torch will represent the numpy default parameter
print(tensor.dtype)

torch.float64


In [148]:
array.dtype # default

dtype('float64')